### ISSUE TITLE
Getting Invalid SQL type: date error queries with declare statements

### ISSUE THREAD

**Issue by TunahanOcal** [GoogleCloudPlatform/zetasql-toolkit#32]
Hello,

I am getting type errors, if the query has declare statements. You can see the example declare statements and the exception below.
```
declare _delta_date_min date;
declare _delta_date_max date;

```
```
Exception in thread "main" com.google.zetasql.toolkit.catalog.typeparser.ZetaSQLTypeParseError: Invalid SQL type: date
	at com.google.zetasql.toolkit.catalog.typeparser.ZetaSQLTypeParser.parse(ZetaSQLTypeParser.java:77)
	at com.google.zetasql.toolkit.ZetaSQLToolkitAnalyzer$StatementAnalyzer.parseASTType(ZetaSQLToolkitAnalyzer.java:253)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.google.zetasql.toolkit.ZetaSQLToolkitAnalyzer$StatementAnalyzer.applyVariableDeclaration(ZetaSQLToolkitAnalyzer.java:285)
	at com.google.zetasql.toolkit.ZetaSQLToolkitAnalyzer$StatementAnalyzer.next(ZetaSQLToolkitAnalyzer.java:195)
	at com.google.zetasql.toolkit.ZetaSQLToolkitAnalyzer$StatementAnalyzer.next(ZetaSQLToolkitAnalyzer.java:148)
```
Thanks in advance.

**Comment by TunahanOcal** [comment]
I just noticed that if the variable types are written in lowercase, errors will occur; whereas, if the types are written in uppercase, there will be no exception.

**Comment by marcinp55** [comment]
I'm getting the same exception and changing the types to uppercase really does solve the problem. Given that SQL is case-insensitive that's quite unexpected.

**Comment by ppaglilla** [comment]
Fixed in https://github.com/GoogleCloudPlatform/zetasql-toolkit/commit/465bcedde61f29d85953b4585039c58dd787619d, will be included in the next release. This release has been a long time coming, but should release shortly.

**Comment by ppaglilla** [comment]
Version `0.5.0` has been released with the fix for this issue and is already available through maven
